{
 "title": "EBay Items",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "itemId", "query": { "query": "label_values(itemId)" } },
   { "name": "sellerUserName", "query": { "query": "label_values(sellerUserName)" } },
   { "name": "categoryName", "query": { "query": "label_values(categoryName)" } },
   {
    "name": "conditionDisplayName",
    "query": {
     "query": "label_values(conditionDisplayName)"
    }
   },
   { "name": "age", "query": { "query": "label_values(age_bucket)" } }
  ]
 },
 "panels": [
  { "title": "Items", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "watchCount by itemId",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by(itemId) (ebay_item_watch_count{categoryName=~\"$categoryName\", itemId=~\"$itemId\", sellerUserName=~\"$sellerUserName\", conditionDisplayName=~\"$conditionDisplayName\", age_bucket=~\"$age\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "watchCount distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by(le) (rate(ebay_item_watch_count_histogram_bucket{categoryName=~\"$categoryName\", itemId=~\"$itemId\", sellerUserName=~\"$sellerUserName\", conditionDisplayName=~\"$conditionDisplayName\", age_bucket=~\"$age\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg watchCount  by categoryName",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "avg by(categoryName) (ebay_item_watch_count{categoryName=~\"$categoryName\", itemId=~\"$itemId\", sellerUserName=~\"$sellerUserName\", conditionDisplayName=~\"$conditionDisplayName\", age_bucket=~\"$age\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Days old distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum by(le) (rate(ebay_item_listing_age_days_histogram_bucket{categoryName=~\"$categoryName\", itemId=~\"$itemId\", sellerUserName=~\"$sellerUserName\", conditionDisplayName=~\"$conditionDisplayName\", age_bucket=~\"$age\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg watchCount by conditionDisplayName",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "avg by(conditionDisplayName) (ebay_item_watch_count{categoryName=~\"$categoryName\", itemId=~\"$itemId\", sellerUserName=~\"$sellerUserName\", conditionDisplayName=~\"$conditionDisplayName\", age_bucket=~\"$age\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Days remaining distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum by(le) (rate(ebay_item_listing_days_remaining_histogram_bucket{categoryName=~\"$categoryName\", itemId=~\"$itemId\", sellerUserName=~\"$sellerUserName\", conditionDisplayName=~\"$conditionDisplayName\", age_bucket=~\"$age\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Seller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Avg watchCount by sellerUserName",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "avg by(sellerUserName) (ebay_item_watch_count{categoryName=~\"$categoryName\", itemId=~\"$itemId\", sellerUserName=~\"$sellerUserName\", conditionDisplayName=~\"$conditionDisplayName\", age_bucket=~\"$age\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg watchCount by postalCode",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "avg by(postalCode) (ebay_item_watch_count{categoryName=~\"$categoryName\", itemId=~\"$itemId\", sellerUserName=~\"$sellerUserName\", conditionDisplayName=~\"$conditionDisplayName\", age_bucket=~\"$age\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg watchCount by feedbackRatingStar",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "avg by(feedbackRatingStar) (ebay_item_watch_count{categoryName=~\"$categoryName\", itemId=~\"$itemId\", sellerUserName=~\"$sellerUserName\", conditionDisplayName=~\"$conditionDisplayName\", age_bucket=~\"$age\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}